### ISSUE TITLE
lolz

### ISSUE THREAD

**Issue by xgraza** [ssllllll/IL-Client-0.2#1]
legit de-compiled and guess what i see: another sad sad sad oyvey rename smh

didnt even bother to change the package names lol

**Comment by xgraza** [comment]
oh it also has three burrow modules. SelfFill, Burrow, and SmartBurrow

**Comment by xgraza** [comment]
atleast 30 packetflys, 3 phase modules. goddamn how many clients did they take a module from and just slap it into an oyvey base

who even made this sad rename?

**Comment by ssllllll** [comment]
HAHAHAHAHHA This rename was made by a shitty taco dev named "Zaka"

**Comment by ssllllll** [comment]
I didnt decompiled and showed the src because i knew this would be a sshitty rename

**Comment by xgraza** [comment]
oh its a shitty shitty shitty rename

![image](https://user-images.githubusercontent.com/57580886/139755234-44ee19f9-c7b6-4a7b-915b-306aec975521.png)

they even took a w+3 speed module xd

w+3 should make their licensing GPL-3.0 so that oyvey renamers cant paste their speed into their sad rename too.

they also just copy pasted Phobos's AutoCrystal into it too while having the OyVey autocyrstal

they pasted phase from w+3 and TuxHack? whatever the fuck that is

every second i look at this shit it makes me loose braincells

**Comment by ssllllll** [comment]
OMFG THAT CLAN IS FULL OF STUPID ASS NONAMERS

**Comment by xgraza** [comment]
i hope to god they werent making you pay for the client either? if so ima decompile and leak the src cause i have nothing better to do and cause their rename is funny asf

**Comment by ssllllll** [comment]
YESS Decompile it


I ratted one of the guys with access to the client so idrc, i ratted him with a SAD SHITTY esohack named Xulu+ 😂 🚬

**Comment by xgraza** [comment]
lmao how do you even like run a client named Xulu+ holy shit what the shit thats just sad omfg

**Comment by ssllllll** [comment]
sad asf 😂

**Comment by ssllllll** [comment]
they were asking me Xulu+ on dms so i sent em the client with a yoinky 😹

**Comment by HausemasterIssue** [comment]
@ssllllll did they have future?

**Comment by AnotherNoName** [comment]
the "dev" zaka, only rename a existing oyvey skid lmfao 😂

**Comment by HausemasterIssue** [comment]
i need a future v2.11.1 dump STAT, did the guy who u yoinked have future?

**Comment by ssllllll** [comment]
> @ssllllll did they have future?

THE POOR AS MF WAS USING CRACKED FUTURE ROFLSAUCE

**Comment by ssllllll** [comment]
> i need a future v2.11.1 dump STAT, did the guy who u yoinked have future?

![image](https://user-images.githubusercontent.com/86989232/139756763-b1ea17c2-10f8-42a2-8440-16135d1de644.png)

**Comment by HausemasterIssue** [comment]
@ssllllll dump future please i beg you

**Comment by ssllllll** [comment]
> i need a future v2.11.1 dump STAT, did the guy who u yoinked have future?

Cracked future 😹 🚬

**Comment by ssllllll** [comment]
> @ssllllll dump future please i beg you

If you decode it its just the path to the cracked future

**Comment by HausemasterIssue** [comment]
lmfao hes double ratted

**Comment by xgraza** [comment]
lol https://github.com/Sxmurai/IL-Client-0.2-decompiled

**Comment by xgraza** [comment]
ima re-decompile with a better decompiler that doesnt make comments everywhere

**Comment by HausemasterIssue** [comment]
another shitty oyvey skid PWNED good job gavin

**Comment by HausemasterIssue** [comment]
@Sxmurai oh god please run it through ModFixer the src is unreadable

**Comment by ssllllll** [comment]
> lmfao hes double ratted

yeah, he also was going to run an OyVey-0.0.4 that was another yoink

**Comment by ssllllll** [comment]
> lol https://github.com/Sxmurai/IL-Client-0.2-decompiled

ez

**Comment by HausemasterIssue** [comment]
@ssllllll if u get ur hands on a future account anytime soon hit me up, i need a dump asap. once i have a dump its only deobfing from there, can you do that?

**Comment by ssllllll** [comment]
sure np

**Comment by HausemasterIssue** [comment]
@ssllllll do u have one rn?

**Comment by ssllllll** [comment]
rn i dont, srry

**Comment by HausemasterIssue** [comment]
ight hit me up when u have one, email me at this email below if u got one

queueskip2b2t@gmail.com

**Comment by ssllllll** [comment]
kk

**Comment by HausemasterIssue** [comment]
@Sxmurai decomped the src from the jar, i used my modfixer so there isnt mc_field_34771 everywhere and the src is actually readble, here's the zip

https://www.mediafire.com/file/9b6ly4w83a5fidf/IL-Client-SRC-Non-Chinese.zip/file

**Comment by xgraza** [comment]
dont worry hause im almost done, i just have to remap it

**Comment by xgraza** [comment]
okay updated https://github.com/Sxmurai/IL-Client-0.2-decompiled thanks @HausemasterIssue
